### ISSUE TITLE
`pdflatex` throws UnboundLocalError

### ISSUE THREAD

**Issue by kennyballou** [devnulltao/Xnt#36]
Here's a stack trace from a current assignment I'm working on::

```
Traceback (most recent call last):
  File "/home/l0x3py/.local/bin/xnt", line 9, in <module>
    load_entry_point('Xnt==0.7.0.dev.alpha', 'console_scripts', 'xnt')()
  File "/home/l0x3py/.local/lib/python3.4/site-packages/Xnt-0.7.0.dev.alpha-py3.4.egg/xnt/xenant.py", line 49, in main
  File "/home/l0x3py/.local/lib/python3.4/site-packages/Xnt-0.7.0.dev.alpha-py3.4.egg/xnt/tasks/__init__.py", line 118, in xntcall
  File "/home/l0x3py/.local/lib/python3.4/site-packages/Xnt-0.7.0.dev.alpha-py3.4.egg/xnt/tasks/core_tasks.py", line 413, in __apply__
  File "/home/l0x3py/.local/lib/python3.4/site-packages/Xnt-0.7.0.dev.alpha-py3.4.egg/xnt/tasks/core_tasks.py", line 287, in __execute__
  File "/home/l0x3py/.local/lib/python3.4/site-packages/Xnt-0.7.0.dev.alpha-py3.4.egg/xnt/tasks/core_tasks.py", line 316, in __run_in__
  File "/home/l0x3py/.local/lib/python3.4/site-packages/Xnt-0.7.0.dev.alpha-py3.4.egg/xnt/tasks/core_tasks.py", line 286, in closure
  File "/home/l0x3py/.local/lib/python3.4/site-packages/Xnt-0.7.0.dev.alpha-py3.4.egg/xnt/tasks/core_tasks.py", line 274, in invoke_build
  File "/home/l0x3py/.local/lib/python3.4/site-packages/Xnt-0.7.0.dev.alpha-py3.4.egg/xnt/tasks/core_tasks.py", line 263, in call_target
  File "/home/l0x3py/.local/lib/python3.4/site-packages/Xnt-0.7.0.dev.alpha-py3.4.egg/xnt/__init__.py", line 87, in wrap
  File "/home/l0x3py/Dev/M465-HW01/build.py", line 17, in build
    xnt.pdflatex('./src/tex/hw01.tex')
  File "/home/l0x3py/.local/lib/python3.4/site-packages/Xnt-0.7.0.dev.alpha-py3.4.egg/xnt/tasks/__init__.py", line 290, in pdflatex
  File "/home/l0x3py/.local/lib/python3.4/site-packages/Xnt-0.7.0.dev.alpha-py3.4.egg/xnt/tasks/core_tasks.py", line 413, in __apply__
  File "/home/l0x3py/.local/lib/python3.4/site-packages/Xnt-0.7.0.dev.alpha-py3.4.egg/xnt/tasks/build/tex.py", line 72, in __execute__
  File "/home/l0x3py/.local/lib/python3.4/site-packages/Xnt-0.7.0.dev.alpha-py3.4.egg/xnt/tasks/build/tex.py", line 53, in pdf
  File "/home/l0x3py/.local/lib/python3.4/site-packages/Xnt-0.7.0.dev.alpha-py3.4.egg/xnt/tasks/core_tasks.py", line 413, in __apply__
  File "/home/l0x3py/.local/lib/python3.4/site-packages/Xnt-0.7.0.dev.alpha-py3.4.egg/xnt/tasks/core_tasks.py", line 340, in __execute__
UnboundLocalError: local variable 'path' referenced before assignment
```

This seems to be thrown regardless of location of the actual \LaTeX{} file, i.e., if tex file to be compiled is in the current working directory or some directory relative of the working directory.

**Comment by kennyballou** [comment]
Turns out to be an issue with improper variable naming/ shadowing in `xnt.core_tasks.__call__`.
